/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#ifndef YAML_LV_STYLE_STYLES_H
#define YAML_LV_STYLE_STYLES_H

namespace ui {

enum class DarkStyle {
    Button,
    Screen,
};

enum class LightStyle {
    Button,
    Screen,
};

}  // namespace ui

#endif  // YAML_LV_STYLE_STYLES_H