/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "styles/stylesheets.h"

#include "styles/stylesheet_dark.h"
#include "styles/stylesheet_light.h"


/**
 * @brief Initializes all dynamic styles of the stylesheets
 */
void init_style_sheets() {
    init_dark_style_sheet();
    init_light_style_sheet();
}