/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "styles/stylesheet_light.h"



// button
const lv_style_const_prop_t button_default_main_props[] = {
    LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
    LV_STYLE_CONST_BG_COLOR(LV_COLOR_MAKE(59, 130, 246)),
    LV_STYLE_CONST_TEXT_COLOR(LV_COLOR_MAKE(241, 245, 249)),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(button_default_main, button_default_main_props);

const lv_style_const_prop_t button_hovered_main_props[] = {
    LV_STYLE_CONST_BG_COLOR(LV_COLOR_MAKE(37, 99, 235)),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(button_hovered_main, button_hovered_main_props);




static lv_style_t screen_default_main;


/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void init_light_style_sheet() {
    // screen
    lv_style_init(&screen_default_main);
    lv_style_set_bg_color(&screen_default_main, lv_color_make(248, 250, 252));
    
}

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void set_light_style(lv_obj_t* obj, light_style_t name) {
    switch (name) {
        case LIGHT_STYLE_BUTTON:
            lv_obj_add_style(obj, &button_default_main, LV_STATE_DEFAULT | LV_PART_MAIN);
            lv_obj_add_style(obj, &button_hovered_main, LV_STATE_HOVERED | LV_PART_MAIN);
        break;
        case LIGHT_STYLE_SCREEN:
            lv_obj_add_style(obj, &screen_default_main, LV_STATE_DEFAULT | LV_PART_MAIN);
        break;
    }
}
/**
 * @brief Gets a style from "light" stylesheet
 * @param name The enum value of the style to apply
 * @param selector The LVGL part and state selector
 * @return The style pointer
 */
lv_style_t* get_light_style(light_style_t name, lv_style_selector_t selector) {
    switch (name) {
        case LIGHT_STYLE_SCREEN:
            switch (selector) {
                case LV_STATE_DEFAULT | LV_PART_MAIN: return &screen_default_main;
                default: return NULL;
            }
        default: return NULL;
    }
}