/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#ifndef YAML_LV_STYLE_STYLESHEETS_H
#define YAML_LV_STYLE_STYLESHEETS_H

#include <lvgl.h>

#include "generated_styles/styles.h"

/**
 * @brief Initializes all dynamic styles of the stylesheets
 */
void initStyleSheets();

/**
 * @brief Applies a style from "dark" stylesheet to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setStyle(lv_obj_t* obj, DarkStyle name);

/**
 * @brief Applies a style from "light" stylesheet to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setStyle(lv_obj_t* obj, LightStyle name);

#endif  // YAML_LV_STYLE_STYLESHEETS_H