/*
 *  Automatically generated file: DO NOT MODIFY
 *  Generated by yaml_lv_style
 */

#ifndef YAML_LV_STYLE_STYLESHEET_DARK_H
#define YAML_LV_STYLE_STYLESHEET_DARK_H

#include <lvgl.h>

#include "generated_styles/styles.h"

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void initDarkStyleSheet();

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setDarkStyle(lv_obj_t*, DarkStyle);

#endif  // YAML_LV_STYLE_STYLESHEET_DARK_H