/*
 *  Automatically generated file: DO NOT MODIFY
 *  Generated by yaml_lv_style
 */

#ifndef YAML_LV_STYLE_STYLES_H
#define YAML_LV_STYLE_STYLES_H

typedef enum {
    GRID_STYLE_CELL_0_0,
    GRID_STYLE_CELL_0_1,
    GRID_STYLE_CELL_1_0,
    GRID_STYLE_CELL_1_1,
    GRID_STYLE_LAYOUT,
} grid_style_t;

#endif  // YAML_LV_STYLE_STYLES_H