/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheet_dark.h"

static lv_style_t button_default;
static lv_style_t button_hovered;
static lv_style_t screen_default;

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void init_dark_stylesheet() {
    // button
    lv_style_init(&button_default);
    lv_style_set_align(&button_default, LV_ALIGN_CENTER);
    lv_style_set_bg_color(&button_default, lv_color_make(30, 41, 59));
    lv_style_set_text_color(&button_default, lv_color_make(241, 245, 249));

    lv_style_init(&button_hovered);
    lv_style_set_bg_color(&button_hovered, lv_color_make(51, 65, 85));

    // screen
    lv_style_init(&screen_default);
    lv_style_set_bg_color(&screen_default, lv_color_make(15, 23, 42));
}

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void set_dark_style(lv_obj_t* obj, dark_style_t name) {
    switch (name) {
        case DARK_STYLE_BUTTON:
            lv_obj_add_style(obj, &button_default, LV_STATE_DEFAULT);
            lv_obj_add_style(obj, &button_hovered, LV_STATE_HOVERED);
            break;
        case DARK_STYLE_SCREEN:
            lv_obj_add_style(obj, &screen_default, LV_STATE_DEFAULT);
            break;
    }
}