/*
 *  Automatically generated file: DO NOT MODIFY
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheets.h"

#include "generated_styles/stylesheet_dark.h"
#include "generated_styles/stylesheet_light.h"

/**
 * @brief Initializes all dynamic styles of the stylesheets
 */
void init_stylesheets() {
    init_dark_stylesheet();
    init_light_stylesheet();
}