/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheet_light.h"

// button
const lv_style_const_prop_t button_default_props[] = {
    LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
    LV_STYLE_CONST_BG_COLOR(LV_COLOR_MAKE(59, 130, 246)),
    LV_STYLE_CONST_TEXT_COLOR(LV_COLOR_MAKE(241, 245, 249)),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(button_default, button_default_props);

const lv_style_const_prop_t button_hovered_props[] = {
    LV_STYLE_CONST_BG_COLOR(LV_COLOR_MAKE(37, 99, 235)),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(button_hovered, button_hovered_props);

static lv_style_t screen_default;

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void init_light_stylesheet() {
    // screen
    lv_style_init(&screen_default);
    lv_style_set_bg_color(&screen_default, lv_color_make(248, 250, 252));
}

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void set_light_style(lv_obj_t* obj, light_style_t name) {
    switch (name) {
        case LIGHT_STYLE_BUTTON:
            lv_obj_add_style(obj, &button_default, LV_STATE_DEFAULT);
            lv_obj_add_style(obj, &button_hovered, LV_STATE_HOVERED);
            break;
        case LIGHT_STYLE_SCREEN:
            lv_obj_add_style(obj, &screen_default, LV_STATE_DEFAULT);
            break;
    }
}