/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#ifndef YAML_LV_STYLE_STYLESHEET_DARK_H
#define YAML_LV_STYLE_STYLESHEET_DARK_H

#include <lvgl.h>

#include "styles/styles.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void init_dark_style_sheet();

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void set_dark_style(lv_obj_t* obj, dark_style_t name);


/**
 * @brief Gets a style from "dark" stylesheet
 * @param name The enum value of the style to apply
 * @param selector The LVGL part and state selector
 * @return The style pointer
 */
lv_style_t* get_dark_style(dark_style_t name, lv_style_selector_t selector);

#ifdef __cplusplus
}
#endif

#endif   // YAML_LV_STYLE_STYLESHEET_DARK_H