/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#ifndef YAML_LV_STYLE_STYLES_H
#define YAML_LV_STYLE_STYLES_H

typedef enum {
    DARK_STYLE_BUTTON,
    DARK_STYLE_SCREEN,
} dark_style_t;

typedef enum {
    LIGHT_STYLE_BUTTON,
    LIGHT_STYLE_SCREEN,
} light_style_t;

#endif  // YAML_LV_STYLE_STYLES_H