/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "styles/stylesheets.h"

#include "styles/stylesheet_dark.h"
#include "styles/stylesheet_light.h"

namespace ui {

/**
 * @brief Initializes all dynamic styles of the stylesheets
 */
void initStyleSheets() {
    initDarkStyleSheet();
    initLightStyleSheet();
}

/**
 * @brief Applies a style from "dark" stylesheet to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setStyle(lv_obj_t* obj, DarkStyle name) {
    setDarkStyle(obj, name);
}

/**
 * @brief Applies a style from "light" stylesheet to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setStyle(lv_obj_t* obj, LightStyle name) {
    setLightStyle(obj, name);
}

/**
 * @brief Gets a style from "dark" stylesheet
 * @param name The enum value of the style to apply
 * @param selector The LVGL part and state selector
 * @return The style pointer
 */
lv_style_t* getStyle(DarkStyle name, lv_style_selector_t selector) {
    return getDarkStyle(name, selector);
}

/**
 * @brief Gets a style from "light" stylesheet
 * @param name The enum value of the style to apply
 * @param selector The LVGL part and state selector
 * @return The style pointer
 */
lv_style_t* getStyle(LightStyle name, lv_style_selector_t selector) {
    return getLightStyle(name, selector);
}

}  // namespace ui
