/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "styles/stylesheet_dark.h"



lv_style_t ButtonDefaultMain;lv_style_t ButtonHoveredMain;
lv_style_t ScreenDefaultMain;




/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void initDarkStyleSheet() {
    // button
    lv_style_init(&ButtonDefaultMain);
    lv_style_set_align(&ButtonDefaultMain, LV_ALIGN_CENTER);
    lv_style_set_bg_color(&ButtonDefaultMain, lv_color_make(30, 41, 59));
    lv_style_set_text_color(&ButtonDefaultMain, lv_color_make(241, 245, 249));
    
    lv_style_init(&ButtonHoveredMain);
    lv_style_set_bg_color(&ButtonHoveredMain, lv_color_make(51, 65, 85));
    
    // screen
    lv_style_init(&ScreenDefaultMain);
    lv_style_set_bg_color(&ScreenDefaultMain, lv_color_make(15, 23, 42));
    
}

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setDarkStyle(lv_obj_t* obj, DarkStyle name) {
    switch (name) {
        case DarkStyle::Button:
            lv_obj_add_style(obj, &ButtonDefaultMain, LV_STATE_DEFAULT | LV_PART_MAIN);
            lv_obj_add_style(obj, &ButtonHoveredMain, LV_STATE_HOVERED | LV_PART_MAIN);
        break;
        case DarkStyle::Screen:
            lv_obj_add_style(obj, &ScreenDefaultMain, LV_STATE_DEFAULT | LV_PART_MAIN);
        break;
    }
}
/**
 * @brief Gets a style from "dark" stylesheet
 * @param name The enum value of the style to apply
 * @param selector The LVGL part and state selector
 * @return The style pointer
 */
lv_style_t* getDarkStyle(DarkStyle name, lv_style_selector_t selector) {
    switch (name) {
        case DarkStyle::Button:
            switch (selector) {
                case LV_STATE_DEFAULT | LV_PART_MAIN: return &ButtonDefaultMain;
                case LV_STATE_HOVERED | LV_PART_MAIN: return &ButtonHoveredMain;
                default: return nullptr;
            }
        case DarkStyle::Screen:
            switch (selector) {
                case LV_STATE_DEFAULT | LV_PART_MAIN: return &ScreenDefaultMain;
                default: return nullptr;
            }
        default: return nullptr;
    }
}

