/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "styles/stylesheet_light.h"


namespace {

// button
const lv_style_const_prop_t ButtonDefaultMainProps[] = {
    LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
    LV_STYLE_CONST_BG_COLOR(LV_COLOR_MAKE(59, 130, 246)),
    LV_STYLE_CONST_TEXT_COLOR(LV_COLOR_MAKE(241, 245, 249)),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(ButtonDefaultMain, ButtonDefaultMainProps);

const lv_style_const_prop_t ButtonHoveredMainProps[] = {
    LV_STYLE_CONST_BG_COLOR(LV_COLOR_MAKE(37, 99, 235)),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(ButtonHoveredMain, ButtonHoveredMainProps);


lv_style_t ScreenDefaultMain;

} // unnamed namespace




/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void initLightStyleSheet() {
    // screen
    lv_style_init(&ScreenDefaultMain);
    lv_style_set_bg_color(&ScreenDefaultMain, lv_color_make(248, 250, 252));
    
}

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setLightStyle(lv_obj_t* obj, LightStyle name) {
    switch (name) {
        case LightStyle::Button:
            lv_obj_add_style(obj, &ButtonDefaultMain, LV_STATE_DEFAULT | LV_PART_MAIN);
            lv_obj_add_style(obj, &ButtonHoveredMain, LV_STATE_HOVERED | LV_PART_MAIN);
        break;
        case LightStyle::Screen:
            lv_obj_add_style(obj, &ScreenDefaultMain, LV_STATE_DEFAULT | LV_PART_MAIN);
        break;
    }
}
/**
 * @brief Gets a style from "light" stylesheet
 * @param name The enum value of the style to apply
 * @param selector The LVGL part and state selector
 * @return The style pointer
 */
lv_style_t* getLightStyle(LightStyle name, lv_style_selector_t selector) {
    switch (name) {
        case LightStyle::Screen:
            switch (selector) {
                case LV_STATE_DEFAULT | LV_PART_MAIN: return &ScreenDefaultMain;
                default: return nullptr;
            }
        default: return nullptr;
    }
}

