/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#ifndef YAML_LV_STYLE_STYLESHEET_LIGHT_H
#define YAML_LV_STYLE_STYLESHEET_LIGHT_H

#include <lvgl.h>

#include "styles/styles.h"

namespace ui {

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void initLightStyleSheet();

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setLightStyle(lv_obj_t* obj, LightStyle name);
/**
 * @brief Gets a style from "light" stylesheet
 * @param name The enum value of the style to apply
 * @param selector The LVGL part and state selector
 * @return The style pointer
 */
lv_style_t* getLightStyle(LightStyle name, lv_style_selector_t selector = LV_PART_MAIN | LV_STATE_DEFAULT);

}  // namespace ui

#endif  // YAML_LV_STYLE_STYLESHEET_LIGHT_H