/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#ifndef YAML_LV_STYLE_STYLESHEETS_H
#define YAML_LV_STYLE_STYLESHEETS_H

#include <lvgl.h>

#include "styles/styles.h"

namespace ui {

/**
 * @brief Initializes all dynamic styles of the stylesheets
 */
void initStyleSheets();


/**
 * @brief Applies a style from "dark" stylesheet to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setStyle(lv_obj_t* obj, DarkStyle name);

/**
 * @brief Applies a style from "light" stylesheet to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setStyle(lv_obj_t* obj, LightStyle name);



/**
 * @brief Gets a style from "dark" stylesheet
 * @param name The enum value of the style to apply
 * @param selector The LVGL part and state selector
 * @return The style pointer
 */
lv_style_t* getStyle(DarkStyle name, lv_style_selector_t selector);

/**
 * @brief Gets a style from "light" stylesheet
 * @param name The enum value of the style to apply
 * @param selector The LVGL part and state selector
 * @return The style pointer
 */
lv_style_t* getStyle(LightStyle name, lv_style_selector_t selector);


} // ui

#endif   // YAML_LV_STYLE_STYLESHEETS_H