/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheet_light.h"

namespace {

// button
const lv_style_const_prop_t ButtonDefaultProps[] = {
    LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
    LV_STYLE_CONST_BG_COLOR(LV_COLOR_MAKE(59, 130, 246)),
    LV_STYLE_CONST_TEXT_COLOR(LV_COLOR_MAKE(241, 245, 249)),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(ButtonDefault, ButtonDefaultProps);

const lv_style_const_prop_t ButtonHoveredProps[] = {
    LV_STYLE_CONST_BG_COLOR(LV_COLOR_MAKE(37, 99, 235)),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(ButtonHovered, ButtonHoveredProps);

lv_style_t ScreenDefault;

}  // unnamed namespace

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void initLightStyleSheet() {
    // screen
    lv_style_init(&ScreenDefault);
    lv_style_set_bg_color(&ScreenDefault, lv_color_make(248, 250, 252));
}

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setLightStyle(lv_obj_t* obj, LightStyle name) {
    switch (name) {
        case LightStyle::Button:
            lv_obj_add_style(obj, &ButtonDefault, LV_STATE_DEFAULT);
            lv_obj_add_style(obj, &ButtonHovered, LV_STATE_HOVERED);
            break;
        case LightStyle::Screen:
            lv_obj_add_style(obj, &ScreenDefault, LV_STATE_DEFAULT);
            break;
    }
}
