/*
 *  Automatically generated file: DO NOT MODIFY
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheet_dark.h"

/**
 * @brief Dynamic style declarations
 * Memory allocation for styles that require runtime initialization.
 */
static lv_style_t buttonDefault;
static lv_style_t buttonHovered;

static lv_style_t screenDefault;

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void initDarkStyleSheet() {
    // --- Definition for dynamic style: button ---
    lv_style_init(&buttonDefault);
    lv_style_set_align(&buttonDefault, LV_ALIGN_CENTER);
    lv_style_set_bg_color(&buttonDefault, lv_color_make(30, 41, 59));
    lv_style_set_text_color(&buttonDefault, lv_color_make(241, 245, 249));

    lv_style_init(&buttonHovered);
    lv_style_set_bg_color(&buttonHovered, lv_color_make(51, 65, 85));

    // --- Definition for dynamic style: screen ---
    lv_style_init(&screenDefault);
    lv_style_set_bg_color(&screenDefault, lv_color_make(15, 23, 42));
}

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setDarkStyle(lv_obj_t* obj, DarkStyle name) {
    switch (name) {
        case DarkStyle::Button:
            lv_obj_add_style(obj, &buttonDefault, LV_STATE_DEFAULT);
            lv_obj_add_style(obj, &buttonHovered, LV_STATE_HOVERED);
            break;
        case DarkStyle::Screen:
            lv_obj_add_style(obj, &screenDefault, LV_STATE_DEFAULT);
            break;
    }
}
