/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheets.h"

#include "generated_styles/stylesheet_dark.h"
#include "generated_styles/stylesheet_light.h"

/**
 * @brief Initializes all dynamic styles of the stylesheets
 */
void initStyleSheets() {
    initDarkStyleSheet();
    initLightStyleSheet();
}

/**
 * @brief Applies a style from "dark" stylesheet to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setStyle(lv_obj_t* obj, DarkStyle name) {
    setDarkStyle(obj, name);
}

/**
 * @brief Applies a style from "light" stylesheet to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setStyle(lv_obj_t* obj, LightStyle name) {
    setLightStyle(obj, name);
}
