/*
 *  Automatically generated file: DO NOT MODIFY
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheet_light.h"

/**
 * @brief Static and constant style definitions
 * Memory allocation for styles that are pre-calculated and stored in Flash/ROM.
 */
namespace {

// --- Definition for constant style: button ---
const lv_style_const_prop_t buttonDefaultProps[] = {
    LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
    LV_STYLE_CONST_BG_COLOR(LV_COLOR_MAKE(59, 130, 246)),
    LV_STYLE_CONST_TEXT_COLOR(LV_COLOR_MAKE(241, 245, 249)),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(buttonDefault, buttonDefaultProps);

const lv_style_const_prop_t buttonHoveredProps[] = {
    LV_STYLE_CONST_BG_COLOR(LV_COLOR_MAKE(37, 99, 235)),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(buttonHovered, buttonHoveredProps);

}  // namespace

/**
 * @brief Dynamic style declarations
 * Memory allocation for styles that require runtime initialization.
 */
static lv_style_t screenDefault;

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void initLightStyleSheet() {
    // --- Definition for dynamic style: screen ---
    lv_style_init(&screenDefault);
    lv_style_set_bg_color(&screenDefault, lv_color_make(248, 250, 252));
}

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setLightStyle(lv_obj_t* obj, LightStyle name) {
    switch (name) {
        case LightStyle::Button:
            lv_obj_add_style(obj, &buttonDefault, LV_STATE_DEFAULT);
            lv_obj_add_style(obj, &buttonHovered, LV_STATE_HOVERED);
            break;
        case LightStyle::Screen:
            lv_obj_add_style(obj, &screenDefault, LV_STATE_DEFAULT);
            break;
    }
}
