/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheet_dark.h"

lv_style_t ButtonDefault;
lv_style_t ButtonHovered;
lv_style_t ScreenDefault;

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void initDarkStyleSheet() {
    // button
    lv_style_init(&ButtonDefault);
    lv_style_set_align(&ButtonDefault, LV_ALIGN_CENTER);
    lv_style_set_bg_color(&ButtonDefault, lv_color_make(30, 41, 59));
    lv_style_set_text_color(&ButtonDefault, lv_color_make(241, 245, 249));

    lv_style_init(&ButtonHovered);
    lv_style_set_bg_color(&ButtonHovered, lv_color_make(51, 65, 85));

    // screen
    lv_style_init(&ScreenDefault);
    lv_style_set_bg_color(&ScreenDefault, lv_color_make(15, 23, 42));
}

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void setDarkStyle(lv_obj_t* obj, DarkStyle name) {
    switch (name) {
        case DarkStyle::Button:
            lv_obj_add_style(obj, &ButtonDefault, LV_STATE_DEFAULT);
            lv_obj_add_style(obj, &ButtonHovered, LV_STATE_HOVERED);
            break;
        case DarkStyle::Screen:
            lv_obj_add_style(obj, &ScreenDefault, LV_STATE_DEFAULT);
            break;
    }
}
