/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheet_grid.h"

static lv_style_t cell_0_0_default;
static lv_style_t cell_0_1_default;
static lv_style_t cell_1_0_default;
static lv_style_t cell_1_1_default;
static lv_style_t layout_default;

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void init_grid_stylesheet() {
    // cell_0_0
    lv_style_init(&cell_0_0_default);
    lv_style_set_grid_cell_column_pos(&cell_0_0_default, 0);
    lv_style_set_grid_cell_row_pos(&cell_0_0_default, 0);
    lv_style_set_grid_cell_x_align(&cell_0_0_default, LV_GRID_ALIGN_STRETCH);
    lv_style_set_grid_cell_y_align(&cell_0_0_default, LV_GRID_ALIGN_STRETCH);

    // cell_0_1
    lv_style_init(&cell_0_1_default);
    lv_style_set_grid_cell_column_pos(&cell_0_1_default, 0);
    lv_style_set_grid_cell_row_pos(&cell_0_1_default, 1);
    lv_style_set_grid_cell_x_align(&cell_0_1_default, LV_GRID_ALIGN_STRETCH);
    lv_style_set_grid_cell_y_align(&cell_0_1_default, LV_GRID_ALIGN_STRETCH);

    // cell_1_0
    lv_style_init(&cell_1_0_default);
    lv_style_set_grid_cell_column_pos(&cell_1_0_default, 1);
    lv_style_set_grid_cell_row_pos(&cell_1_0_default, 0);
    lv_style_set_grid_cell_x_align(&cell_1_0_default, LV_GRID_ALIGN_STRETCH);
    lv_style_set_grid_cell_y_align(&cell_1_0_default, LV_GRID_ALIGN_STRETCH);

    // cell_1_1
    lv_style_init(&cell_1_1_default);
    lv_style_set_grid_cell_column_pos(&cell_1_1_default, 1);
    lv_style_set_grid_cell_row_pos(&cell_1_1_default, 1);
    lv_style_set_grid_cell_x_align(&cell_1_1_default, LV_GRID_ALIGN_STRETCH);
    lv_style_set_grid_cell_y_align(&cell_1_1_default, LV_GRID_ALIGN_STRETCH);

    // layout
    static const int32_t grid_column_dsc_array_layout_default[] = {100, LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    static const int32_t grid_row_dsc_array_layout_default[] = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
    lv_style_init(&layout_default);
    lv_style_set_align(&layout_default, LV_ALIGN_CENTER);
    lv_style_set_grid_column_dsc_array(&layout_default, grid_column_dsc_array_layout_default);
    lv_style_set_grid_row_dsc_array(&layout_default, grid_row_dsc_array_layout_default);
    lv_style_set_height(&layout_default, 200);
    lv_style_set_layout(&layout_default, LV_LAYOUT_GRID);
    lv_style_set_width(&layout_default, 275);
}

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void set_grid_style(lv_obj_t* obj, grid_style_t name) {
    switch (name) {
        case GRID_STYLE_CELL_0_0:
            lv_obj_add_style(obj, &cell_0_0_default, LV_STATE_DEFAULT);
            break;
        case GRID_STYLE_CELL_0_1:
            lv_obj_add_style(obj, &cell_0_1_default, LV_STATE_DEFAULT);
            break;
        case GRID_STYLE_CELL_1_0:
            lv_obj_add_style(obj, &cell_1_0_default, LV_STATE_DEFAULT);
            break;
        case GRID_STYLE_CELL_1_1:
            lv_obj_add_style(obj, &cell_1_1_default, LV_STATE_DEFAULT);
            break;
        case GRID_STYLE_LAYOUT:
            lv_obj_add_style(obj, &layout_default, LV_STATE_DEFAULT);
            break;
    }
}