/*
 *  Automatically generated file: DO NOT MODIFY
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheet_grid.h"

/**
 * @brief Static and constant style definitions
 * Memory allocation for styles that are pre-calculated and stored in Flash/ROM.
 */

// --- Definition for constant style: cell_0_0 ---
const lv_style_const_prop_t cell_0_0_default_props[] = {
    LV_STYLE_CONST_GRID_CELL_COLUMN_POS(0),
    LV_STYLE_CONST_GRID_CELL_ROW_POS(0),
    LV_STYLE_CONST_GRID_CELL_X_ALIGN(LV_GRID_ALIGN_STRETCH),
    LV_STYLE_CONST_GRID_CELL_Y_ALIGN(LV_GRID_ALIGN_STRETCH),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(cell_0_0_default, cell_0_0_default_props);

// --- Definition for constant style: cell_0_1 ---
const lv_style_const_prop_t cell_0_1_default_props[] = {
    LV_STYLE_CONST_GRID_CELL_COLUMN_POS(0),
    LV_STYLE_CONST_GRID_CELL_ROW_POS(1),
    LV_STYLE_CONST_GRID_CELL_X_ALIGN(LV_GRID_ALIGN_STRETCH),
    LV_STYLE_CONST_GRID_CELL_Y_ALIGN(LV_GRID_ALIGN_STRETCH),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(cell_0_1_default, cell_0_1_default_props);

// --- Definition for constant style: cell_1_0 ---
const lv_style_const_prop_t cell_1_0_default_props[] = {
    LV_STYLE_CONST_GRID_CELL_COLUMN_POS(1),
    LV_STYLE_CONST_GRID_CELL_ROW_POS(0),
    LV_STYLE_CONST_GRID_CELL_X_ALIGN(LV_GRID_ALIGN_STRETCH),
    LV_STYLE_CONST_GRID_CELL_Y_ALIGN(LV_GRID_ALIGN_STRETCH),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(cell_1_0_default, cell_1_0_default_props);

// --- Definition for constant style: cell_1_1 ---
const lv_style_const_prop_t cell_1_1_default_props[] = {
    LV_STYLE_CONST_GRID_CELL_COLUMN_POS(1),
    LV_STYLE_CONST_GRID_CELL_ROW_POS(1),
    LV_STYLE_CONST_GRID_CELL_X_ALIGN(LV_GRID_ALIGN_STRETCH),
    LV_STYLE_CONST_GRID_CELL_Y_ALIGN(LV_GRID_ALIGN_STRETCH),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(cell_1_1_default, cell_1_1_default_props);

// --- Definition for constant style: layout ---
const lv_style_const_prop_t layout_default_props[] = {
    LV_STYLE_CONST_ALIGN(LV_ALIGN_CENTER),
    LV_STYLE_CONST_GRID_COLUMN_DSC_ARRAY(((const int32_t[]){100, LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST})),
    LV_STYLE_CONST_GRID_ROW_DSC_ARRAY(((const int32_t[]){LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST})),
    LV_STYLE_CONST_HEIGHT(200),
    LV_STYLE_CONST_LAYOUT(LV_LAYOUT_GRID),
    LV_STYLE_CONST_WIDTH(275),
    LV_STYLE_CONST_PROPS_END,
};
LV_STYLE_CONST_INIT(layout_default, layout_default_props);

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void set_grid_style(lv_obj_t* obj, grid_style_t name) {
    switch (name) {
        case GRID_STYLE_CELL_0_0:
            lv_obj_add_style(obj, &cell_0_0_default, LV_STATE_DEFAULT);
            break;
        case GRID_STYLE_CELL_0_1:
            lv_obj_add_style(obj, &cell_0_1_default, LV_STATE_DEFAULT);
            break;
        case GRID_STYLE_CELL_1_0:
            lv_obj_add_style(obj, &cell_1_0_default, LV_STATE_DEFAULT);
            break;
        case GRID_STYLE_CELL_1_1:
            lv_obj_add_style(obj, &cell_1_1_default, LV_STATE_DEFAULT);
            break;
        case GRID_STYLE_LAYOUT:
            lv_obj_add_style(obj, &layout_default, LV_STATE_DEFAULT);
            break;
    }
}