/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#include "generated_styles/stylesheets.h"

#include "generated_styles/stylesheet_grid.h"

/**
 * @brief Initializes all dynamic styles of the stylesheets
 */
void init_stylesheets() {
    init_grid_stylesheet();
}