/*
 *  Automatically generated file
 *  DO NOT MODIFY: changes will be overwritten
 *  Generated by yaml_lv_style
 */

#ifndef YAML_LV_STYLE_STYLESHEET_LIGHT_H
#define YAML_LV_STYLE_STYLESHEET_LIGHT_H

#include <lvgl.h>

#include "generated_styles/styles.h"

/**
 * @brief Initializes all dynamic styles in the stylesheet
 * Sets properties at runtime for styles not marked as 'const'.
 */
void init_light_stylesheet();

/**
 * @brief Applies a style to a given LVGL object
 * @param obj The LVGL object pointer
 * @param name The enum value of the style to apply
 */
void set_light_style(lv_obj_t* obj, light_style_t name);

#endif  // YAML_LV_STYLE_STYLESHEET_LIGHT_H